import React from 'react';
import { Card } from './Card';
import { Download } from 'lucide-react';

export const Scorecard = ({
    damageScore = 92,
    typographyCrimes = 14,
    colorClashes = 8,
    alignmentErrors = 9000,
    roast = "It looks like a wireframe that started drinking at noon.",
    tier = 'free',
    scansUsed = 1,
    scansLimit = 5,
    errors = []
}) => {
    // Generate PDF/text download
    const handleDownload = () => {
        const content = `
╔═══════════════════════════════════════════════════════════════╗
║                    PIXELROAST DAMAGE REPORT                    ║
╚═══════════════════════════════════════════════════════════════╝

EMOTIONAL DAMAGE SCORE: ${damageScore}%
STATUS: ${damageScore > 80 ? 'CRITICAL' : damageScore > 50 ? 'CONCERNING' : 'MILD'}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

DAMAGE BREAKDOWN:
  • Typography Crimes ........ ${typographyCrimes}
  • Color Clashes ............ ${colorClashes}
  • Alignment Errors ......... ${alignmentErrors > 100 ? 'Over 9000' : alignmentErrors}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

THE VERDICT:
"${roast}"

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

ISSUES FOUND (${errors.length}):
${errors.map((e, i) => `  ${i + 1}. ${e}`).join('\n') || '  None detected (suspicious...)'}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Tier: ${tier?.toUpperCase() || 'FREE'}
Scans: ${scansUsed || 0}/${scansLimit || 5}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Generated by PixelRoast - Emotional Damage On Demand
https://pixelroast.pages.dev

No website was harmed in the making of this roast.
(Your feelings, however, are not our responsibility.)
        `.trim();

        const blob = new Blob([content], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = 'pixelroast-damage-report.txt';
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    return (
        <Card className="h-full bg-brutalist-black text-white p-0 overflow-hidden sticky top-24">
            <div className="p-6 border-b-2 border-white/20 bg-neutral-900">
                <h3 className="text-2xl uppercase tracking-widest text-brutalist-red font-black">
                    Damage Report
                </h3>
            </div>

            <div className="p-6 space-y-6">
                {/* Damage Score */}
                <div className="text-center">
                    <p className="text-sm font-mono text-gray-400 mb-2 uppercase">Emotional Damage</p>
                    <div className="relative inline-block">
                        <span className="text-6xl font-black text-brutalist-red">{damageScore}%</span>
                        <span className="absolute -top-2 -right-6 text-2xl animate-pulse">💔</span>
                    </div>
                    <p className="text-xs font-mono text-red-500 mt-2">
                        {damageScore > 80 ? 'CRITICAL LEVELS DETECTED' : damageScore > 50 ? 'CONCERNING DAMAGE' : 'MILD PAIN'}
                    </p>
                </div>

                {/* Stats */}
                <div className="space-y-3 font-mono text-sm">
                    <div className="flex justify-between border-b border-white/10 pb-2">
                        <span className="text-gray-400">Typography Crimes</span>
                        <span className="text-white font-bold">{typographyCrimes}</span>
                    </div>
                    <div className="flex justify-between border-b border-white/10 pb-2">
                        <span className="text-gray-400">Color Clashes</span>
                        <span className="text-white font-bold">{colorClashes}</span>
                    </div>
                    <div className="flex justify-between border-b border-white/10 pb-2">
                        <span className="text-gray-400">Alignment Errors</span>
                        <span className="text-white font-bold">{alignmentErrors > 100 ? 'Over 9000' : alignmentErrors}</span>
                    </div>
                </div>

                {/* Verdict Quote */}
                <div className="bg-white/5 p-4 border border-white/10">
                    <p className="text-brutalist-red font-bold text-xs uppercase mb-2">Verdict</p>
                    <p className="text-sm font-bold leading-tight">
                        "{roast?.substring(0, 120)}{roast?.length > 120 ? '...' : ''}"
                    </p>
                </div>

                {/* Usage */}
                <div className="flex items-center justify-between text-xs font-mono text-gray-500">
                    <span>Tier: {tier?.toUpperCase() || 'FREE'}</span>
                    <span>Scans: {scansUsed || 0}/{scansLimit || 5}</span>
                </div>
            </div>

            {/* Download Button */}
            <div className="p-4 bg-red-900/20 border-t border-white/10">
                <button
                    onClick={handleDownload}
                    className="w-full py-3 bg-white text-black font-black uppercase tracking-tight hover:bg-brutalist-red hover:text-white transition-colors flex items-center justify-center gap-2"
                >
                    <Download size={18} />
                    Download Shame.pdf
                </button>
            </div>
        </Card>
    );
};
